export const ACADEMIES = [
  'Aix-Marseille',
  'Amiens',
  'Besançon',
  'Bordeaux',
  'Caen',
  'Clermont-Ferrand',
  'Corse',
  'Créteil',
  'Dijon',
  'Grenoble',
  'Guadeloupe',
  'Guyane',
  'La Réunion',
  'Lille',
  'Limoges',
  'Lyon',
  'Martinique',
  'Mayotte',
  'Montpellier',
  'Nancy-Metz',
  'Nantes',
  'Nice',
  'Normandie',
  'Nouvelle-Calédonie',
  'Orléans-Tours',
  'Paris',
  'Poitiers',
  'Polynésie française',
  'Reims',
  'Rennes',
  'Saint-Pierre-et-Miquelon',
  'Strasbourg',
  'Toulouse',
  'Versailles',
  'Wallis-et-Futuna',
] as const

export type Academy = (typeof ACADEMIES)[number]

export const SUBJECTS = [
  'Mathématiques',
  'Français',
  'Lettres classiques',
  'Lettres modernes',
  'Histoire-Géographie',
  'Anglais',
  'Espagnol',
  'Allemand',
  'Arabe',
  'Portugais',
  'Physique-Chimie',
  'Sciences de la vie et de la Terre',
  'Sciences économiques et sociales',
  'Philosophie',
  'Éducation physique et sportive',
  'Arts plastiques',
  'Éducation musicale',
  'Technologie',
  'Sciences de l\'ingénieur',
  'Informatique / NSI',
  'Latin',
  'Grec ancien',
  'Sciences de gestion / STMG',
  'Biotechnologies / ST2S',
  'STI2D',
  'Primaire / Polyvalent',
  'Maternelle',
  'SEGPA / ASH',
  'Documentation',
  'Conseiller principal d\'éducation',
  'FLE / FLS',
  'Autre',
] as const

export type Subject = (typeof SUBJECTS)[number]

// Catégories d'annonces (taxonomie fixe pour la recherche)
export const POST_CATEGORIES = [
  'Cours & éducation',
  'Logement & échange',
  'Biens (achat/vente)',
  'Services',
] as const
